
baseurl: "https://uncv2022.github.io"
color-scheme: "#1a2090" #the scheme can be any HEX code like "#334279"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

title: "Workshop on Uncertainty Quantification for Computer Vision"
subtitle: "ECCV 2022 Workshop"

shorttitle: "UNCV Workshop @ ECCV 2022"
information: "ECCV 2022 Workshop on Uncertainty Quantification for Computer Vision." 

organizers: "UNCV Organizers"

deadlines:
  - item: Submission deadline
    date: TBA
  
  - item: Notification of acceptance
    date: TBA

  - item: Camera-ready deadline
    date: July 17, 2022

